version: '3.8'

services:
  apache-with-php:
    build: ./docker-images/apache-with-php
    volumes:
      - ./www:/var/www/html/
    ports:
      - "80:80"
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
