version: '2'

services:
  ngnix:
    image: ${NGINX_IMAGE}
    container_name: personal-website-ngnix
    ports:
      - "80:80"
    volumes:
      - ../src:/src
      - ../nginx/config/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - personal-website-network
  php:
    image: ${PHP_IMAGE}
    container_name: personal-website-php
    volumes:
      - ../src:/src
    networks:
      - personal-website-network

networks:
  personal-website-network:
    driver: bridge
